// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configuration for Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQOsuyU83AMKs9jNqMM5ZqHZ_VswTqWcM',
    appId: '1:515120820798:web:fcf9891eb605d39e78576f',
    messagingSenderId: '515120820798',
    projectId: 'scc-app-21367',
    authDomain: 'scc-app-21367.firebaseapp.com',
    storageBucket: 'scc-app-21367.firebasestorage.app',
  );

  // Configuration for Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsugAX2GeibU4PNhNwHjSHpqyRjsyNMAQ',
    appId: '1:515120820798:android:983022dc2ce76af978576f',
    messagingSenderId: '515120820798',
    projectId: 'scc-app-21367',
    storageBucket: 'scc-app-21367.firebasestorage.app',
  );

  // Configuration for iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0O36ORBgskxuUKJ38bSGJmI5hQZa7S4Q',
    appId: '1:515120820798:ios:5002b2d1ee60341578576f',
    messagingSenderId: '515120820798',
    projectId: 'scc-app-21367',
    storageBucket: 'scc-app-21367.firebasestorage.app',
    iosBundleId: 'com.example.sccApp',
  );
}